/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_liga;

import domain.Liga;
import forme.MainForm;
import javax.swing.JOptionPane;
import models.TableModelLige;

/**
 *
 * @author Viktor
 */
public class FormPretragaLige extends javax.swing.JDialog {

    public FormPretragaLige(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga lige");
        TableModelLige model = new TableModelLige();
        Thread th = new Thread(model);
        th.start();
        tblLige.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLige = new javax.swing.JTable();
        txtNazivLige = new javax.swing.JTextField();
        btnDetalji = new javax.swing.JButton();
        txtNazivDrzave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga (naziv lige):");

        tblLige.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLige);

        txtNazivLige.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivLigeKeyReleased(evt);
            }
        });

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDetalji.setText("Detalji lige");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        txtNazivDrzave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivDrzaveKeyReleased(evt);
            }
        });

        jLabel2.setText("Pretraga (naziv drzave):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNazivDrzave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(txtNazivLige))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivLige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNazivLigeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivLigeKeyReleased
        String parametarNazivLige = txtNazivLige.getText();
        TableModelLige tm = (TableModelLige) tblLige.getModel();
        tm.setParametarNazivLige(parametarNazivLige);

       if (tm.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje igrace po zadatim vrednostima!",
                   "Obavestenje", JOptionPane.ERROR_MESSAGE);
      } else {
           JOptionPane.showMessageDialog(this,
                   "Sistem je pronasao igrace po zadatim vrednostima!");
       }
    }//GEN-LAST:event_txtNazivLigeKeyReleased

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        int row = tblLige.getSelectedRow();

        if (row >= 0) {
            Liga liga = ((TableModelLige) tblLige.getModel()).getSelectedLiga(row);
            new FormDetaljiLige(this, true, liga).setVisible(true);
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void txtNazivDrzaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivDrzaveKeyReleased
        String parametarNazivDrzave = txtNazivDrzave.getText();
        TableModelLige tm = (TableModelLige) tblLige.getModel();
        tm.setParametarNazivDrzave(parametarNazivDrzave);

       if (tm.getLista().isEmpty()) {          JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje igrace po zadatim vrednostima!",
                    "Obavestenje", JOptionPane.ERROR_MESSAGE);
        } else {
           JOptionPane.showMessageDialog(this,
                    "Sistem je pronasao igrace po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtNazivDrzaveKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLige;
    private javax.swing.JTextField txtNazivDrzave;
    private javax.swing.JTextField txtNazivLige;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        TableModelLige tm = (TableModelLige) tblLige.getModel();
        tm.refreshTable();
    }

    void popuniLige() {
        MainForm mf = (MainForm) getParent();
        mf.popuniLige();
    }

}
