/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_tim;

import domain.Tim;
import javax.swing.JOptionPane;
import models.TableModelTimovi;

/**
 *
 * @author Viktor
 */
public class FormPretragaTima extends javax.swing.JDialog {

    public FormPretragaTima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga tima");
        TableModelTimovi model = new TableModelTimovi();
        Thread th = new Thread(model);
        th.start();
        tblTimovi.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimovi = new javax.swing.JTable();
        txtNazivTima = new javax.swing.JTextField();
        btnDetalji = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNazivLige = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtImeStatisticara = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrezimeStatisticara = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga (naziv tima):");

        tblTimovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTimovi);

        txtNazivTima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivTimaKeyReleased(evt);
            }
        });

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDetalji.setText("Detalji tima");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        jLabel2.setText("Pretraga (naziv lige):");

        txtNazivLige.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivLigeKeyReleased(evt);
            }
        });

        jLabel3.setText("Pretraga (ime statisticara):");

        txtImeStatisticara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtImeStatisticaraKeyReleased(evt);
            }
        });

        jLabel4.setText("Pretraga (prezime statisticara):");

        txtPrezimeStatisticara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrezimeStatisticaraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNazivLige, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(80, 80, 80)
                                .addComponent(txtNazivTima))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtImeStatisticara)
                                    .addComponent(txtPrezimeStatisticara))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivTima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNazivLige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImeStatisticara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezimeStatisticara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        int row = tblTimovi.getSelectedRow();

        if (row >= 0) {
            Tim t = ((TableModelTimovi) tblTimovi.getModel()).getSelectedTim(row);
            new FormDetaljiTima(this, true, t).setVisible(true);
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void txtNazivLigeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivLigeKeyReleased
        String nazivLige = txtNazivLige.getText();
        TableModelTimovi tm = (TableModelTimovi) tblTimovi.getModel();
        tm.setParametarNazivLige(nazivLige);

       if (tm.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje timove po zadatim vrednostima!",
                   "Obavestenje", JOptionPane.ERROR_MESSAGE);
       } else {
            JOptionPane.showMessageDialog(this,
                    "Sistem je pronasao timove po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtNazivLigeKeyReleased

    private void txtImeStatisticaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImeStatisticaraKeyReleased
        String ime = txtImeStatisticara.getText();
        TableModelTimovi tm = (TableModelTimovi) tblTimovi.getModel();
        tm.setParametarIme(ime);

       if (tm.getLista().isEmpty()) {
           JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje timove po zadatim vrednostima!",
                   "Obavestenje", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                   "Sistem je pronasao timove po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtImeStatisticaraKeyReleased

    private void txtPrezimeStatisticaraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrezimeStatisticaraKeyReleased
        String prezime = txtPrezimeStatisticara.getText();
        TableModelTimovi tm = (TableModelTimovi) tblTimovi.getModel();
        tm.setParametarPrezime(prezime);

       if (tm.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje timove po zadatim vrednostima!",
                    "Obavestenje", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Sistem je pronasao timove po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtPrezimeStatisticaraKeyReleased

    private void txtNazivTimaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivTimaKeyReleased
        String nazivTima = txtNazivTima.getText();
        TableModelTimovi tm = (TableModelTimovi) tblTimovi.getModel();
        tm.setParametarNazivTima(nazivTima);

       if (tm.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Sistem ne moze da pronadje timove po zadatim vrednostima!",
                   "Obavestenje", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                    "Sistem je pronasao timove po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtNazivTimaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTimovi;
    private javax.swing.JTextField txtImeStatisticara;
    private javax.swing.JTextField txtNazivLige;
    private javax.swing.JTextField txtNazivTima;
    private javax.swing.JTextField txtPrezimeStatisticara;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        TableModelTimovi tm = (TableModelTimovi) tblTimovi.getModel();
        tm.refreshTable();
    }

}
