/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_drzava;

import domain.Drzava;

import forme.MainForm;
import javax.swing.JOptionPane;
import models.TableModelDrzava;



/**
 *
 * @author Viktor
 */
public class FormPretragaDrzava extends javax.swing.JDialog {

    public FormPretragaDrzava(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pretraga drzave");
        TableModelDrzava model = new TableModelDrzava();
        Thread th = new Thread(model);
        th.start();
        tblDrzava.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrzava = new javax.swing.JTable();
        btnDetalji = new javax.swing.JButton();
        txtNazivDrzave = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pretraga (naziv):");

        tblDrzava.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDrzava);

        btnDetalji.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDetalji.setText("Detalji drzave");
        btnDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetaljiActionPerformed(evt);
            }
        });

        txtNazivDrzave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNazivDrzaveActionPerformed(evt);
            }
        });
        txtNazivDrzave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNazivDrzaveKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnDetalji, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNazivDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNazivDrzave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalji)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetaljiActionPerformed

        int row = tblDrzava.getSelectedRow();

        if (row >= 0) {
           Drzava d = ((TableModelDrzava) tblDrzava.getModel()).getSelectedDrzava(row);
            new FormDetaljiIDrzava(this, true, d).setVisible(true);
        }

    }//GEN-LAST:event_btnDetaljiActionPerformed

    private void txtNazivDrzaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNazivDrzaveKeyReleased
       String parametarNazivDrzave = txtNazivDrzave.getText();
        TableModelDrzava tm = (TableModelDrzava) tblDrzava.getModel();
        tm.setParametarNazivDrzave(parametarNazivDrzave);
        
        
        
        
        if (tm.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                   "Sistem ne moze da pronadje drzave po zadatim vrednostima!",
                    "Obavestenje", JOptionPane.ERROR_MESSAGE);
        } else {
          JOptionPane.showMessageDialog(this,
                   "Sistem je pronasao drzavu po zadatim vrednostima!");
        }
    }//GEN-LAST:event_txtNazivDrzaveKeyReleased

    private void txtNazivDrzaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNazivDrzaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNazivDrzaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDrzava;
    private javax.swing.JFormattedTextField txtNazivDrzave;
    // End of variables declaration//GEN-END:variables

    void refreshTable() {
        TableModelDrzava tm = (TableModelDrzava) tblDrzava.getModel();
        tm.refreshTable();
    }



    void popuniDrzavu() {
        MainForm mf= (MainForm) getParent();
        mf.popuniLige();
    }

}
