/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import controller.ClientController;
import domain.Drzava;
import domain.Igrac;
import domain.Liga;
import domain.Statisticar;
import domain.StavkaTima;
import domain.Tim;
import form_drzava.FormNovaDrzava;
import form_drzava.FormPretragaDrzava;
import form_igrac.FormNoviIgrac;
import form_igrac.FormPretragaIgraca;
import form_liga.FormNovaLiga;
import form_liga.FormPretragaLige;
import form_tim.FormPretragaTima;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelStavkeTima;
import session.Session;

/**
 *
 * @author Viktor 
 */
public class MainForm extends javax.swing.JFrame {

    private Statisticar ulogovani;
    private int brojIgraca;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani statisticar: " + ulogovani);
        setTitle("Klijentska forma");
        txtBrojIgraca.setEditable(false);
        popuniIgrace();
        popuniLige();
       
        tblStavke.setModel(new TableModelStavkeTima());

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovani);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbLiga = new javax.swing.JComboBox();
        txtNaziv = new javax.swing.JTextField();
        txtBrojIgraca = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDodajClana = new javax.swing.JButton();
        btnObrisiClana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        cmbIgrac = new javax.swing.JComboBox();
        txtBrojDresa = new javax.swing.JTextField();
        cmbPozicija = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNovaLiga = new javax.swing.JMenuItem();
        miPretragaLige = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNoviIgrac = new javax.swing.JMenuItem();
        miPretragaIgraca = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaTima = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tim"));

        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSacuvaj.setText("Sacuvaj tim");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Liga:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Broj igraca:");

        cmbLiga.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNaziv.setText("Tim 1");

        txtBrojIgraca.setText("10");
        txtBrojIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojIgracaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clanovi tima"));

        jLabel6.setText("Igrac:");

        jLabel7.setText("Broj na dresu:");

        jLabel9.setText("Pozicija:");

        btnDodajClana.setText("Dodaj clana tima");
        btnDodajClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajClanaActionPerformed(evt);
            }
        });

        btnObrisiClana.setText("Obrisi clana tima");
        btnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiClanaActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        cmbIgrac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtBrojDresa.setText("1");

        cmbPozicija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plejmejker", "Bek šuter", "Krilni centar", "Centar", "Krilo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDodajClana, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiClana, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBrojDresa)
                            .addComponent(cmbPozicija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbIgrac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbIgrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBrojDresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajClana)
                    .addComponent(btnObrisiClana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbLiga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNaziv)
                            .addComponent(txtBrojIgraca))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbLiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtBrojIgraca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu6.setText("Liga");

        miNovaLiga.setText("Nova liga");
        miNovaLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovaLigaActionPerformed(evt);
            }
        });
        jMenu6.add(miNovaLiga);

        miPretragaLige.setText("Pretraga lige");
        miPretragaLige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaLigeActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaLige);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Igrac");

        miNoviIgrac.setText("Novi igrac");
        miNoviIgrac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviIgracActionPerformed(evt);
            }
        });
        jMenu8.add(miNoviIgrac);

        miPretragaIgraca.setText("Pretraga igraca");
        miPretragaIgraca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaIgracaActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaIgraca);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Tim");

        miPretragaTima.setText("Pretraga tima");
        miPretragaTima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaTimaActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaTima);

        jMenuBar1.add(jMenu9);

        jMenu2.setText("Drzava");

        jMenuItem1.setText("Nova drzava");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Pretraga drzava");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUlogovani)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNovaLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovaLigaActionPerformed
        new FormNovaLiga(this, true).setVisible(true);
    }//GEN-LAST:event_miNovaLigaActionPerformed

    private void miPretragaLigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaLigeActionPerformed
        new FormPretragaLige(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaLigeActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNoviIgracActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviIgracActionPerformed
        new FormNoviIgrac(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviIgracActionPerformed

    private void miPretragaIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaIgracaActionPerformed
        new FormPretragaIgraca(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaIgracaActionPerformed

    private void miPretragaTimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaTimaActionPerformed
        new FormPretragaTima(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaTimaActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            if (txtNaziv.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti naziv tima!");
                return;
            }

            Liga liga = (Liga) cmbLiga.getSelectedItem();
            String naziv = txtNaziv.getText();

            TableModelStavkeTima tm = (TableModelStavkeTima) tblStavke.getModel();

            Tim tim = new Tim(null, naziv, tm.getLista().size(), 0, 0, liga, ulogovani,
                    tm.getLista());

            ClientController.getInstance().addTim(tim);
            txtBrojIgraca.setText("");
            txtNaziv.setText("");
            tm.getLista().clear();
            tm.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio tim!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            //            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnDodajClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajClanaActionPerformed

        if (txtBrojDresa.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti broj dresa i broj izostanaka!");
            return;
        }

        int brojDresa = Integer.parseInt(txtBrojDresa.getText());

        if (brojDresa < 1 || brojDresa > 99) {
            JOptionPane.showMessageDialog(this, "Broj dresa mora biti izmedju 1 i 99!");
            return;
        }

        Igrac igrac = (Igrac) cmbIgrac.getSelectedItem();
        String pozicija = (String) cmbPozicija.getSelectedItem();

        StavkaTima st = new StavkaTima(null, -1, brojDresa, pozicija, igrac);

        TableModelStavkeTima tm = (TableModelStavkeTima) tblStavke.getModel();

        if (tm.postojiBrojDresa(brojDresa)) {
            JOptionPane.showMessageDialog(this, "Vec postoji igrac sa tim brojem dresa!");
            return;
        }

        if (tm.postojiIgrac(igrac)) {
            JOptionPane.showMessageDialog(this, "Vec ste uneli tog igraca!");
            return;
        }

        tm.dodajStavku(st);

        brojIgraca = tm.getLista().size();
        txtBrojIgraca.setText(String.valueOf(brojIgraca));

    }//GEN-LAST:event_btnDodajClanaActionPerformed

    private void btnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiClanaActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeTima tm = (TableModelStavkeTima) tblStavke.getModel();
            tm.obrisiStavku(row);
            brojIgraca = tm.getLista().size();
            txtBrojIgraca.setText(String.valueOf(brojIgraca));
        }
    }//GEN-LAST:event_btnObrisiClanaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new FormNovaDrzava(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new FormPretragaDrzava(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtBrojIgracaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojIgracaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojIgracaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajClana;
    private javax.swing.JButton btnObrisiClana;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbIgrac;
    private javax.swing.JComboBox cmbLiga;
    private javax.swing.JComboBox cmbPozicija;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNovaLiga;
    private javax.swing.JMenuItem miNoviIgrac;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaIgraca;
    private javax.swing.JMenuItem miPretragaLige;
    private javax.swing.JMenuItem miPretragaTima;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojDresa;
    private javax.swing.JTextField txtBrojIgraca;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables

    public void popuniIgrace() {
        try {
            ArrayList<Igrac> igraci = ClientController.getInstance()
                    .getAllIgrac(new Igrac(null, "", "", 0));

            cmbIgrac.removeAllItems();

            for (Igrac igrac : igraci) {
                cmbIgrac.addItem(igrac);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniLige() {
        try {
            ArrayList<Liga> lige = ClientController.getInstance()
                    .getAllLiga(new Liga(null, "", new Drzava(null, "")));

            cmbLiga.removeAllItems();

            for (Liga liga : lige) {
                cmbLiga.addItem(liga);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  

}
